services:
  frontend:
    build: 
      context: frontend
      dockerfile: Dockerfile
    depends_on: [mongodb,backend]
    ports:
      - "3000:3000"

  backend:    
    build:
      context: backend
      dockerfile: Dockerfile  
      
    ports:
      - "5000:5000"  
    environment:
      # MongoDB URL
      - DBURL=mongodb://mongodb:27017
      # NodeMailer
      - HOST_EMAIL=your_host_email
      - PASSWORD=your_app_password
      - PORT=587

      # Stripe
      - STRIPE_SECRET_KEY=your_stripe_secret_key

      # Backend server after deployment
      -  DOMAIN=your_domain

      # JWT Secret for encryption
      - SECRET=your_secret_key

      # Notification
      - WHATSAPP=your_whatsapp_api_token

  mongodb:

    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=mongoroot
    #volumes:
    #  - "./data/MongoDB:/data/db"
        