services:
  frontend:
    build: 
      context: frontend
      dockerfile: Dockerfile
    depends_on: [backend]
    ports:
      - "3000:3000"

  backend:    
    build:
      context: backend
      dockerfile: Dockerfile  
      
    ports:
      - "5000:5000"  
    environment:
      # MongoDB URL
      - DBURL=mongodb+srv://<MongoDB ATLAS CONNECTION STRING>
      # NodeMailer
      - HOST_EMAIL=your_host_email
      - PASSWORD=your_app_password
      - PORT=587

      # Stripe
      - STRIPE_SECRET_KEY=your_stripe_secret_key

      # Backend server after deployment
      -  DOMAIN=your_domain

      # JWT Secret for encryption
      - SECRET=your_secret_key

      # Notification
      - WHATSAPP=your_whatsapp_api_token

        